# Final Project: Dancing Ghost!

For our final project in Lets Print Robots we will make a dancing ghost robot. 

![](dancingGhostImage/0-FinishedGhost.jpg)

![](dancingGhostImage/0-FinishedMech.jpg)

\pagebreak

# Step 1

Make a box 20 x 40 x 14

![](dancingGhostImage/1-Screenshot from 2023-12-12 13-39-11.png)

put a small hole in the coner of the block. This will be  used for allignment later. 

![](dancingGhostImage/1-Screenshot from 2023-12-12 13-39-32.png)

Group the hole to the block

![](dancingGhostImage/1-Screenshot from 2023-12-12 13-44-05.png)


\pagebreak

# Step 2

Add the servo vitamin

![](dancingGhostImage/2-Screenshot from 2023-12-12 13-40-46.png)

Make it a hole

![](dancingGhostImage/2-Screenshot from 2023-12-12 13-41-19.png)

Rotate the servo so the cord is pointing towards the calibration pin and the top of the servo is on the same side of the block as the calibraation pin.

Use the allign toop to allign the top of the servo to the top of the block

![](dancingGhostImage/2-Screenshot from 2023-12-12 13-42-45.png)

Select both the block and the servo and move it down to the bed

![](dancingGhostImage/2-Screenshot from 2023-12-12 13-43-11.png)

Use the allign tool to allign the top of the servo to the side with the calibration pin. Allign the right side of the servo to the right side of the block. 

![](dancingGhostImage/2-Screenshot from 2023-12-12 13-44-47.png)

Select just the servo. Set the snap grid to 1mm and move 5mm up. Set the snap grid to 0.5mm and move 1.5mm to the left.

![](dancingGhostImage/2-Screenshot from 2023-12-12 13-45-25.png)


\pagebreak

# Step 3

Import the Bolt and the heat set insert vitamin 

![](dancingGhostImage/3-Screenshot from 2023-12-12 14-00-23.png)

Reorent the bolt

![](dancingGhostImage/3-Screenshot from 2023-12-12 14-00-38.png)

Allign the bolt and insert on center, then group them, then make them a hole

![](dancingGhostImage/3-Screenshot from 2023-12-12 14-01-06.png)

Make two copies


![](dancingGhostImage/3-Screenshot from 2023-12-12 14-02-00.png)

Allign them on top of each other

![](dancingGhostImage/3-Screenshot from 2023-12-12 14-02-14.png)

Use the arrow keys to move the bolts 28.5mm apart and then group them together

![](dancingGhostImage/3-Screenshot from 2023-12-12 14-03-52.png)

Make a second copy of the screws.

![](dancingGhostImage/3-Screenshot from 2023-12-12 14-07-08.png)

Move screws into place on either side of the servo

![](dancingGhostImage/3-Screenshot from 2023-12-12 14-08-11.png)

\pagebreak

# Step 4

Make a cover plate for the servo 35mm by 20mm by 2mm

it should be 2mm thick

![](dancingGhostImage/08.png)

Use the bottom of the bracket to allign the 2 remaining bolt-insert assemblies

![](dancingGhostImage/09.png)

Group the 2 alligned bolts to the cover plate

![](dancingGhostImage/10.png)

Add your name to the cover plate and to the bracket

![](dancingGhostImage/11.png)

Move the cover plate away from the bracket and place it on the print surface

![](dancingGhostImage/12.png)

Make 3 copies of the cover plate

![](dancingGhostImage/13.png)

\pagebreak

# Step 5

Copy and paste the servo block and rotate it 120 degrees

![](dancingGhostImage/14.png)

use the corner pin to visually allign the 2 servo blocks

![](dancingGhostImage/15.png)

Copy and paste the servo block, this time rotate -120 degrees

![](dancingGhostImage/16.png)

use the allignment hole to visually allign the third block

![](dancingGhostImage/17.png)

Make a 10 x 10 x 14mm cylinder 

![](dancingGhostImage/18.png)

Move it to the middle of the 3 blocks

![](dancingGhostImage/19.png)

Group the 3 blocks and support cylinder

![](dancingGhostImage/20.png)

\pagebreak

# Step 6

Use the Spring vitamin to cut a small divit in the center of the servo blocks

![](dancingGhostImage/22.png)

Load the horn vitamin and make it a hole

![](dancingGhostImage/23.png)

Make the block 2mm bigger than the horn in  x and y, and exactly the same height. Allign on centers with the horn

![](dancingGhostImage/24.png)

\pagebreak

# Step 7

Bring in the ball chain vitamin and make it a hole

![](dancingGhostImage/25.png)

Make a cylinder that is 5.5x5.5x the height of the horn block

![](dancingGhostImage/26.png)

Move the ball chain into place so it cuts a recess for the balls on either side of the support cylender

![](dancingGhostImage/27.png)

Make a small cube hole to cut out the path for the cord to travil through during assembly

the cube should be 7 x 4.7 x 2 mm

![](dancingGhostImage/28.png)

![](dancingGhostImage/29.png)

![](dancingGhostImage/30.png)

\pagebreak

# Step 8

Duplicate the ball chain connection for use on the end effector

![](dancingGhostImage/31.png)

This is a model of a Pancil. Make it a hole. 

![](dancingGhostImage/32.png)

Bring in a half-sphere zided 20x20x10

Allign the pencil and the hemisphere

![](dancingGhostImage/33.png)

Drop the spring down so it is just 1 mm above the grid

![](dancingGhostImage/34.png)

Select the pencil, the spring and the hemisphere and using the allign tool, allign all 3 to the center in X and Y

![](dancingGhostImage/35.png)

\pagebreak

# Step 9

Group the ball chain and the block from step 7 and angle it to 45 degrees

raise it up so it is aligned to the hemisphere as shown

![](dancingGhostImage/36.png)

Make 3 coppies after tilting the ballchain

![](dancingGhostImage/37.png)

Rotate the 2 copies to 120 and -120 respectivly

use the points of the hexagon to allign them to to the end effector

![](dancingGhostImage/38.png)

use the ring shape with a tube of 2.75 and 20 x 20 size

![](dancingGhostImage/39.png)

raise the ring up 6 mm


![](dancingGhostImage/40.png)

Allign the ring to the middle of the end effector

![](dancingGhostImage/41.png)

Group the end effector together to finish it. 

![](dancingGhostImage/42.png)

\pagebreak

# Step 10

Arrange the print bed so all the items are within a 120 x 90 mm footprint

![](dancingGhostImage/43.png)
