name: "Release"
on: 
   push:
       tags:       
         - '*'

jobs:

  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
            submodules: recursive 
      - run: sudo apt update;sudo apt -y install texlive-latex-extra
      - run: wget https://github.com/jgm/pandoc/releases/download/3.1.7/pandoc-3.1.7-1-amd64.deb
      - run: sudo dpkg -i pandoc-3.1.7-1-amd64.deb
      - run: echo $PWD
      - run: ls -al ./
      - run: cd ScratchWorksheets/;sed -i 's/VERSIONNUMBER/${{  github.ref_name }}/g' SaveAndLoad.tex
      - run: cd ScratchWorksheets/;pdflatex -jobname=SaveAndLoad-${{  github.ref_name }} SaveAndLoad.tex
      - run: ls -al .
      - run: pandoc  --standalone  --self-contained  --embed-resources --from markdown --output=Overview-${{  github.ref_name }}.pdf README.md
      - run: pandoc  --standalone  --self-contained  --embed-resources --from markdown --output=LetsMakeNametags-${{  github.ref_name }}.pdf makeNametags.md
      - run: pandoc  --standalone  --self-contained  --embed-resources --from markdown --output=DancingGhost-${{  github.ref_name }}.pdf DancingGhost.md
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
              draft: false
              prerelease: false
              release_name: ${{ steps.get_version.outputs.VERSION }}
              tag_name: ${{ github.ref }}
        env:
              GITHUB_TOKEN: ${{ github.token }}
              
      - name: Upload PDF
        uses: actions/upload-release-asset@v1
        env:
              GITHUB_TOKEN: ${{ github.token }}
        with:
              upload_url: ${{ steps.create_release.outputs.upload_url }}
              asset_path: Overview-${{  github.ref_name }}.pdf
              asset_name: Overview-${{  github.ref_name }}.pdf
              asset_content_type: application/binary
      - name: Upload Scratch Save
        uses: actions/upload-release-asset@v1
        env:
              GITHUB_TOKEN: ${{ github.token }}
        with:
              upload_url: ${{ steps.create_release.outputs.upload_url }}
              asset_path: ScratchWorksheets/SaveAndLoad-${{  github.ref_name }}.pdf
              asset_name: ScratchWorksheets/SaveAndLoad-${{  github.ref_name }}.pdf
              asset_content_type: application/binary
      - name: Upload PDF2
        uses: actions/upload-release-asset@v1
        env:
              GITHUB_TOKEN: ${{ github.token }}
        with:
              upload_url: ${{ steps.create_release.outputs.upload_url }}
              asset_path: LetsMakeNametags-${{  github.ref_name }}.pdf
              asset_name: LetsMakeNametags-${{  github.ref_name }}.pdf
              asset_content_type: application/binary
      - name: Upload PDF3
        uses: actions/upload-release-asset@v1
        env:
              GITHUB_TOKEN: ${{ github.token }}
        with:
              upload_url: ${{ steps.create_release.outputs.upload_url }}
              asset_path: DancingGhost-${{  github.ref_name }}.pdf
              asset_name: DancingGhost-${{  github.ref_name }}.pdf
              asset_content_type: application/binary
